services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - apiNetwork

  # api:

  # TODO: fix this service to prod (use tls and other settings)
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: always
    user: 1000:1000
    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_sub",
          "-p",
          "1880",
          "-t",
          "$$SYS/#",
          "-C",
          "1",
          "-i",
          "healthcheck",
          "-W",
          "3",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./config:/mosquitto/config:z"
      - "log:/mosquitto/log"
      - "data:/mosquitto/data"

volumes:
  postgres_data:
  data:
  log:

networks:
  apiNetwork:
